apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: port
spec:
  collectors:
    - tcpPortStatus:
        collectorName: k8s
        port: 7443
  analyzers:
    - tcpPortStatus:
        collectorName: k8s
        outcomes:
          - fail:
              when: "refused"
              message: Connection to port 7443 was refused. Check your firewall.
          - fail:
              when: "unavailable"
              message: Another process was already listening on port 7443.
          - fail:
              when: "timeout"
              message: Timed out connecting to port 7443. Check your firewall.
          - pass:
              when: "open"
              message: Port 7443 is open
          - warn:
              message: Unexpected port status
