apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: example
spec:
  collectors:
    - tcpLoadBalancer:
        collectorName: LB1
        address: 10.1.1.1
        port: 6443
        timeout: 5000ms
    - diskUsage:
        collectorName: ephemeral
        path: /var/lib/kubelet
  analyzers:
    - cpu:
        outcomes:
          - fail:
              when: "< 4"
              message: This server has less than 4 CPU cores, and we require 8, but recommend 16
          - warn:
              when: "< 16"
              message: This server has at least 4 CPU cores, but we recommend 16 or more
          - pass:
              message: This server has sufficient CPU cores
    - tcpLoadBalancer:
        collectorName: LB1
        outcomes:
          - fail:
              when: "connection-timeout"
              message: The TCP Load Balancer is not forwarding traffic to this server.
          - fail:
              when: "address-in-use"
              message: The local port is not available to validate the Load Balancer configuration.
          - pass:
              when: "connected"
              message: The specified TCP Load Balancer appears to be properly forwarding traffic to this server.
    - diskUsage:
        collectorName: ephemeral
        outcomes:
          - fail:
              when: "total < 20Gi"
              message: /var/lib/kubelet has less than 20Gi of total space
          - fail:
              when: "available < 10Gi"
              message: /var/lib/kubelet has less than 10Gi of disk space available
          - fail:
              when: "used/total > 70%"
              message: /var/lib/kubelet is more than 70% full
          - pass:
              message: /var/lib/kubelet has sufficient disk space available
